### PR TITLE
responsive product pages!! (smoothie and dumpling)

### PR DESCRIPTION
**Pull request by jaimanm**
Hey, almost done here with the responsive stuff! This one is the product pages, smoothie.astro and dumpling.astro. There's a really small addition to the tailwind.css file as well but its small.

Sorry to be issuing all these PRs at the same time but I'm locked in today and want to get these done. Would love to help you out if you have any questions!

### CODE REVIEW

**Review by JanaviChadha — COMMENTED** [review]
This text is hard to read bc it spans the background change - I'd add it to the blue background portion ( this is for both smoothies + dumplings )

image

I'd also reccomend changing the icon for "automated blending/dumpling process" to something other than the lightbulb, same for "quick and efficent service"

**Review by tomschmitz98 — CHANGES_REQUESTED** [review]
Icons are distorted in iPhone 11 Pro IOS 14.6 when in horizontal mode (dumpling)

Screen Shot 2024-06-23 at 02 19 42

Icons are distorted in iPhone 11 Pro IOS 14.6 horizontal mode. Also, icon text boxes are in the wrong locations (smoothie)


Screen Shot 2024-06-23 at 02 22 34

**Comment by jaimanm** [comment]
Screenshot 2024-06-24 at 3 38 42 PM

This is the best I can do without putting in excessive work on this.

**Review by tomschmitz98 — APPROVED** [review]
Looks good!

**Review by JanaviChadha — APPROVED** [review]
approved - looks great!

**Pull request merged**
