### PR TITLE
responsive design for the home page!

### PR DESCRIPTION
**Pull request by jaimanm**
Documentation linked here: https://orble.atlassian.net/wiki/x/AQC6BQ

Please make sure that you are reviewing the home page, excluding the Header and Footer since that was done in a previous PR already (that PR is not merged yet so the header and footer will not be responsive in this PR's deployment previews).

Please contact me (Jaiman) with any questions, and have fun with this!

### CODE REVIEW

**Review by JanaviChadha — COMMENTED** [review]
This approval does not include comments on the header and footer in mobile. 

Could this read more button be moved slightly up? It looks odd with there being more empty space above it than below it 
image

Other than that looks great!

**Review by tomschmitz98 — CHANGES_REQUESTED** [review]
iPhone 11 Pro IOS 14.6 Quotes are messed up in both vertical and horizontal modes
Screenshot from 2024-06-23 02-01-20
Screenshot from 2024-06-23 02-05-16

**Review by JanaviChadha — COMMENTED** [review]
The comment text is too small now 

image

I'd increase the text size so it fills the box 

Other than that looks so good!

**Review by tomschmitz98 — CHANGES_REQUESTED** [review]
Problem still remains with:
- Galaxy Note 20 Android 11
- Galaxy Note 20 Ultra Android 11
- Galaxy S10/S10+ Android 11
- Galaxy S20 Android 11
- Galaxy S20 Ultra Android 11
- iPad iPadOS 14.7.1
- iPhone 11 Pro IOS 14.6
- iPhone 11 Pro Max IOS 14.6
- iPhone 12/13+ Pro IOS 14.6
- iPhone 12/13 mini IOS 14.6
- iPhone 12/13 Pro Max IOS 14.6
- iPhone SE 2nd gen IOS 14.6
- Kindle Fire HDX Linux

It mainly occurs with horizontal mode, but I've also seen it happen in vertical mode. For repeatability, I have been using firefox.

Screen Shot 2024-06-23 at 11 05 25
Screen Shot 2024-06-23 at 11 07 00
Screen Shot 2024-06-23 at 11 08 23
Screen Shot 2024-06-23 at 11 11 24
Screen Shot 2024-06-23 at 11 13 01

**Review by tomschmitz98 — APPROVED** [review]
Looks good. You may want to document the issue with firefox when testing responsive design somewhere within confluence.

**Pull request merged**
