### PR TITLE
responsive about page!

### PR DESCRIPTION
**Pull request by jaimanm**
Hi, this is another PR for responsive design for the about page!!!

Documentation for this one is coming soon

### CODE REVIEW

**Review by JanaviChadha — COMMENTED** [review]
The font here could be decreased - its a bit large for mobile 
image

**Review by tomschmitz98 — CHANGES_REQUESTED** [review]
iPhone 11 Pro IOS 14.6 Vertical mode

"Our history" conflicts with above text.
Screenshot from 2024-06-23 02-13-40

**Review by JanaviChadha — COMMENTED** [review]
Change Tom's Image + Update Team Members

**Review by tomschmitz98 — CHANGES_REQUESTED** [review]
Missing image for Boning Zhang. Looks like he has an image in confluence.

**Pull request merged**
